#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

NAME=logbot
DAEMON=/usr/bin/logbot.py
PIDFILE=/var/run/logbot.pid

test -x $DAEMON || exit 5

case $1 in
	start)
		log_daemon_msg "Starting IRC chan logger" "logbot"
   		start-stop-daemon --start --pidfile $PIDFILE --make-pidfile --background -x $DAEMON
		status=$?
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping IRC chan logger" "logbot"
  		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		pidofproc -p $PIDFILE $DAEMON >/dev/null
		status=$?
		if [ $status -eq 0 ]; then
			log_success_msg "logbot is running"
		else
			log_failure_msg "logbot is not running"
		fi
		exit $status
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
